In [75]:
import numpy as np

# Constructeurs Classiques

Le constructeur numpy "np.array" fonctionne en passant 1 paramètre. Il faut donc les imbriqués dans un tableau

In [76]:
a = np.array([1, 2, 3, 4, 5, 6])
# a = a.reshape(a.shape[0], 1)
a

array([1, 2, 3, 4, 5, 6])

Constructeur np.zeros et np.onces, prend en paramètres un tuple.

In [77]:
b = np.zeros((3, 2)) # Same as onces
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Constructeur full

In [78]:
full = np.full((2, 4), 4)
full

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

Constructeur random, s’initialize avec deux paramètres. Les nombres aléatoires sont initialiser avec la distribution de la loi normale.
On peut fixer une seed pour figer l’aléatoire.

In [79]:
np.random.seed(0) # Permet de figer l’aléatoire 
random = np.random.randn(2, 5)
random

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ]])

# Constructeurs utiles avec matplotlib

Le constructeur linspace permet de construire un tableau d’une dimension. Il prend un paramètre de début, de fin et le nombre de point qui va être attribué de manière égale.

In [80]:
linspace = np.linspace(0, 10, 10)
linspace

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

Le constructeur arange permet de construire un tableau de 1 dimension. On spécifie la plage de nombre avec un minimum et un maximum, le troisième paramètre permet de spécifier le pas, en fonction du pas, la taille de la matrice est différente

In [81]:
arange = np.arange(0, 10, 0.5)
arange

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Nous pouvons aussi choisir la structure de donnée, comme en rust, en précisent les bytes et types de données que nous voulons générer

In [82]:
u8 = np.linspace(1, 10, dtype=np.int8)
u8 # Ne générera donc pas de float

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10],
      dtype=int8)

# Les méthodes de manipulations

### Assemblage

In [99]:
A = np.zeros((3, 2))
B = np.ones((3, 2))
C = np.full((3, 2), 2)
A.shape, B.shape, C.shape

((3, 2), (3, 2), (3, 2))

On peut assembler de manière horizontale ou verticale h et v stack

In [93]:
hstack = np.hstack((A, B))
vstack = np.vstack((A, B))
"hstack : ", hstack.shape, "vstack : ", vstack.shape

('hstack : ', (3, 4), 'vstack : ', (6, 2))

Méthode concatenate : Elle permet de coller des matrices selon un axe, peut importe la dimensions. Elle est donc indispancable pour les matrices à plus de 2 dimensions. On utilise l’attribut axis.

In [120]:
D = np.concatenate((A, B, C), axis=1)
D

array([[0., 0., 1., 1., 2., 2.],
       [0., 0., 1., 1., 2., 2.],
       [0., 0., 1., 1., 2., 2.]])

## Reshape

On utilise un tuple comme paramètre, pour effectuer un reshape de manière dynamique, on utilise la shape à l’index 0 pour prendre le nombre d’élément (peut importe la taille). On utilise 1 en second argument, ce qui permet est souvent effectué pour utiliser la matrice dans un algo.

In [115]:
R = np.array([1, 2, 3])
print("Before reshape : ", R.shape)
R = R.reshape((R.shape[0], 1))
"After Reshape : ", R.shape

Before reshape :  (3,)


('After Reshape : ', (3, 1))

## Squeeze

Méthode qui permet d’envelever le second paramètre de la matrice pour, par exemple, afficher une image sans problème.

In [117]:
R = R.squeeze()
R.shape

(3,)

## Ravel

Méthode qui permet d’applatir un tableau en une seule dimension

In [122]:
D.ravel() # D était une matrice (3, 6)

array([0., 0., 1., 1., 2., 2., 0., 0., 1., 1., 2., 2., 0., 0., 1., 1., 2.,
       2.])

## Exercice

Créer une méthode qui permet de générer une matrice aléatoire, prenant m et n paramètre, retournant une matrice m, n+1, biais (remplis de 1)

In [292]:
def initialisation(m, n):
    X = np.random.randn(m, n)
    X = np.concatenate(( X, np.ones((X.shape[0], 1))) , axis=1 )
    return X

In [296]:
random_matrix = initialisation(6, 2)
random_matrix

array([[ 0.68111945,  0.42044483,  1.        ],
       [ 0.2946563 , -0.28267906,  1.        ],
       [-0.22252296,  0.09978125,  1.        ],
       [ 0.26324245,  0.06312253,  1.        ],
       [ 1.82830745, -1.30759389,  1.        ],
       [-0.05750078, -0.46631509,  1.        ]])

In [268]:
W = np.random.randint(0, 255, [1024, 720])
W

array([[101, 123, 197, ..., 177,  87,  57],
       [208,  41, 218, ..., 190, 196, 169],
       [208, 144, 185, ..., 220,  47,  48],
       ...,
       [150, 233, 106, ..., 100, 171,  92],
       [ 51,  42, 247, ..., 236,  15, 197],
       [ 72, 211, 150, ..., 225, 131,  29]])

In [267]:
W[(W<5) & W>2] = 11
W

array([[0, 9, 0, 2, 8],
       [3, 0, 8, 8, 1],
       [0, 5, 8, 2, 3],
       [5, 3, 8, 6, 4],
       [6, 3, 6, 2, 6]])